CREATE TABLE IF NOT EXISTS USERS (
    USER_ID bigint NOT NULL AUTO_INCREMENT,
    USERNAME varchar(255) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(12) NOT NULL,
    ABOUT_ME VARCHAR(100),
    IMAGE VARCHAR(255),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS QUESTIONS (
    QUESTIONS_ID bigint NOT NULL AUTO_INCREMENT,
    USER_ID bigint NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT VARCHAR(255) NOT NULL,
    POSTDATE TIMESTAMP,
    IMAGE VARCHAR(255),
    PRIMARY KEY (QUESTIONS_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE IF NOT EXISTS QUESTIONS_LIKES (
    QUESTIONS_LIKE_ID BIGINT NOT NULL AUTO_INCREMENT,
    RECOMMEND INT NOT NULL,
    USER_ID BIGINT NOT NULL,
    QUESTIONS_ID BIGINT NOT NULL,
    PRIMARY KEY (QUESTIONS_LIKE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (QUESTIONS_ID) REFERENCES QUESTIONS (QUESTIONS_ID)
);

CREATE TABLE IF NOT EXISTS ANSWERS (
    ANSWER_ID bigint NOT NULL AUTO_INCREMENT,
    CONTENT varchar(255) NOT NULL,
    IAMGE VARCHAR(255),
    POSTDATE TIMESTAMP NOT NULL,
    ISCHOICED BOOLEAN,
    PRIMARY KEY (ANSWER_ID)
);

CREATE TABLE IF NOT EXISTS ANSWERS_LIKES (
    ANSWER_LIKE_ID BIGINT NOT NULL AUTO_INCREMENT,
    RECOMMEND INT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ANSWER_ID BIGINT NOT NULL,
    PRIMARY KEY (ANSWER_LIKE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (ANSWER_ID) REFERENCES ANSWERS (ANSWER_ID)
);

